"""tickets, ticket_events, approvals

Revision ID: c7cefaf17891
Revises:
Create Date: 2026-07-04 09:11:31.448415

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c7cefaf17891"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tickets",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("type", sa.Enum("idea", "epic", "task", name="ticket_type"), nullable=False),
        sa.Column("parent_id", sa.String(), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "proposed",
                "exec_review",
                "awaiting_human_go",
                "approved",
                "planning",
                "ready",
                "in_progress",
                "in_qa",
                "done",
                "bounced",
                "escalated",
                "blocked",
                "cancelled",
                name="ticket_state",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("spec", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("acceptance_criteria", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("assignee_agent", sa.String(), nullable=True),
        sa.Column("budget_usd", sa.Numeric(), nullable=True),
        sa.Column("spent_usd", sa.Numeric(), nullable=False),
        sa.Column("bounce_count", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["tickets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "approvals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticket_id", sa.String(), nullable=False),
        sa.Column(
            "gate",
            sa.Enum("idea", "budget", "deploy", "escalation", name="approval_gate"),
            nullable=False,
        ),
        sa.Column("decided_by", sa.String(), nullable=False),
        sa.Column(
            "decision", sa.Enum("approved", "rejected", name="approval_decision"), nullable=False
        ),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("ts", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ticket_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticket_id", sa.String(), nullable=False),
        sa.Column("ts", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("message", "tool_call", "test_result", "transition", "cost", name="event_kind"),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
    # Backs human-readable ticket IDs ("T-001" style); shared across types so numbering
    # reflects creation order rather than being contiguous per type.
    op.execute("CREATE SEQUENCE ticket_seq")


def downgrade() -> None:
    op.execute("DROP SEQUENCE ticket_seq")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ticket_events")
    op.drop_table("approvals")
    op.drop_table("tickets")
    # ### end Alembic commands ###
    # create_table() creates these native enum types implicitly; drop_table() does not
    # implicitly drop them, so remove them explicitly to make downgrade fully reversible.
    enum_names = ("event_kind", "approval_decision", "approval_gate", "ticket_state", "ticket_type")
    for enum_name in enum_names:
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
